### PR TITLE
Updated Java Doc with better description and examples of presenters, …

### PR DESCRIPTION
**Pull request by eppleton**
…Libraries and related projects.

### CODE REVIEW

**Comment by lbruun** [comment]
Hint:   `<p>` ... `</p>`  is not required. Simply just use `<p>` when you want to start a new paragraph. If you insist on using both a start and an end tag then you are making it harder for yourself as they need to balance.

**Comment by JaroslavTulach** [comment]
I don't see anything wrong on using more  `XHTML`-like syntax.

**Comment by JaroslavTulach** [comment]
Thanks guys. Please continue to enhance the documentation, it is important source of information.

**Comment by eppleton** [comment]
Great, seems the merge worked!!

 

--Toni

 

Von: Jaroslav Tulach <notifications@github.com>
Antworten an: apache/incubator-netbeans-html4j <reply@reply.github.com>
Datum: KW 45,Dienstag, 7. November 2017 um 09:38
An: apache/incubator-netbeans-html4j <incubator-netbeans-html4j@noreply.github.com>
Cc: Anton Epple <toni.epple@eppleton.de>, Author <author@noreply.github.com>
Betreff: Re: [apache/incubator-netbeans-html4j] Updated Java Doc with better description and examples of presenters, … (#1)

 

Thanks guys. Please continue to enhance the documentation, it is important source of information.

**Comment by lbruun** [comment]
Valid XHTML definitely not wrong. I guess it is a matter of religion. 

I tend to agree with [Stephen Colebourne](http://blog.joda.org/2012/11/javadoc-coding-standards.html)  :

> **Use simple HTML tags, not valid XHTML**
> 
> Javadoc uses HTML tags to identify paragraphs and other elements. Many developers get drawn to 
> the thought that XHTML is necessarily best, ensuring that all tags open and close correctly. This is a 
> mistake. XHTML adds many extra tags that make the Javadoc harder to read as source code. The 
> Javadoc parser will interpret the incomplete HTML tag soup just fine. 

and as far as I can tell the official advice from Oracle is (still) also to use a single `<p>`, even in JDK8 and JDK9.

Personally, I would say just pick a style and stay with it and it this sense this PR was different from the rest of the html4j code base. Not important, just a comment.
Looking forward to more html4j releases !  :-)

**Pull request merged**
