### PR TITLE
Missing Audio object caused exception

### PR DESCRIPTION
**Pull request by JaroslavTulach**
While playing with my [fair minesweeper](http://github.com/jtulach/minesweeper) game I realized that  missing `Audio` object causes script errors. Changing the check to `typeof Audio === 'object'`. Thanks for your review.

### CODE REVIEW

**Comment by jtulach** [comment]
Review, anyone?

**Comment by geertjanw** [comment]
A check has failed, otherwise it looks fine.

**Comment by matthiasblaesing** [comment]
Looks good - the change looks reasonable. I did not deeply look into the changed regarding the pom.xml. The unittests run cleanly after restarting them.

**Comment by JaroslavTulach** [comment]
Thanks for review and restarting the travis build. I'm going to integrate now.

**Pull request merged**
