### PR TITLE
Renames project to NetBeans Web Toolkit

### PR DESCRIPTION
**Pull request by emilianbold**
This is just a basic rename, more should be changed about the way the project is presented and explained...

### CODE REVIEW

**Comment by jtulach** [comment]
This would solve [NETBEANS-143](https://issues.apache.org/jira/browse/NETBEANS-143) quite nicely. I like the idea. Similar renaming should then be applied to [main repository](http://github.com/apache/incubator-netbeans) as well.

**Comment by neilcsmith-net** [comment]
+1 to changing the name, _possibly_ -1 to that name.  Using "web" seems confusing here?  What's wrong with HTML or HTML UI?

It's similar to concerns people brought up in https://github.com/apache/incubator-netbeans/pull/466 and on the mailing list.

**Comment by geertjanw** [comment]
"Web Apache NetBeans Toolkit" would enable us to talk about the WANT stack vs. the WAMP stack, as well as enable us to have t-shirts with the slogan "Tell us what you WANT, what you really really WANT." (https://www.youtube.com/watch?v=gJLIiF15wjQ)

**Comment by emilianbold** [comment]
Let's just call it **NetBeans Proton** in line with https://electronjs.org :-)

Right now we have only 2 ports: we support the native desktop browser or the desktop JavaFX browser.

So, we can only create desktop apps with Java, Javascript, HTML and CSS.

With the Dukescript non-Apache ports users could create Android/iOS apps too.

I'm not too attached with NetBeans Web Toolkit but any name that starts with 'NetBeans' is better than HTML/Java API.

**Comment by neilcsmith-net** [comment]
To be clear, I was meaning NetBeans HTML UI Toolkit or such.  Or something that doesn't imply this is only about websites.

Surely we should be going deeper than Electron - NetBeans Tau anyone? :wink:

**Comment by emilianbold** [comment]
My comparison was with Google Web Toolkit. I guess I could also use GWT to create an HTML UI and load that in a JavaFX web view or inside Android, but it's essentially creating a web app.

NetBeans Web Toolkit seems descriptive enough.

NetBeans Proton/Tau needs a secondary explanation for people to figure it out. The parallel with Electron might help.

Other idea: `NetBeans Web Platform`? Although this library doesn't seem like a big platform...

Anyhow, I don't want to discuss this very much. Feel free to have a vote or whatever and I'm fine with any new name that you guys pick. I should probably close this PR until a new name is decided upon.

**Comment by neilcsmith-net** [comment]
> My comparison was with Google Web Toolkit.

This was my first comparison with that name too, which is actually my issue with it, because I'm not sure that comparison helps with presenting what this library does / is for?  Given previous mailing list confusion around this, just thinking that (a quick!) discussion about whether that name helps understanding or not might be warranted?  Anyway, that's my 2c - not going to say anything further here, except that this library is great and I think we need to improve how we promote its usage.

**Comment by emilianbold** [comment]
> This was my first comparison with that name too, which is actually my issue with it, because I'm not sure that comparison helps with presenting what this library does / is for?

If it's of any help, I'm also trying to figure out what the library does / is for :-)

Maybe HTML/Java API is the perfect description.

**Comment by vieiro** [comment]
What about "NetBeans Webview API"? AFAIK this is what the project is about: a common way to render apps in different webview implementations (Android/iOS/JavaFX). Note that you don't necessarily render HTML in webviews, you can render SVG as well, right?

**Comment by emilianbold** [comment]
Closing this until a name is decided.

**Pull request closed without merging**
